### ISSUE TITLE
Help in converting List<String> into List<MultiSelectItem>

### ISSUE THREAD

**Issue by Kishan-Somaiya** [CHB61/multi_select_flutter#10]
Hi, can you help me converting a list of string into list of MultiSelectItem.
Here's my list List of String:

List<String> keywords = [Doctor,Engineer,Accountant];

and what should I put in initial value parameter ?

and lastly, thanks  for this amazing package.

**Comment by CHB61** [comment]
Hi @Kishan-Somaiya,

To convert a list of strings to list of MultiSelectItems:
```dart
List keywords = ["Doctor","Engineer","Accountant"];
List<MultiSelectItem> _items = keywords.map((keyword) => MultiSelectItem(keyword, keyword)).toList();
```

Regarding initialValue, it depends on your use case.  Typically you will set it to the list of selected values. For more information on the initialValue parameter please review my comments in this issue:

[initialValue not working as expected #5](https://github.com/CHB61/multi_select_flutter/issues/5)

**Comment by Kishan-Somaiya** [comment]
Thanks for your reply @CHB61 . Can you hekp me one more thing ? How can I show a a certain amount of items(chips) below MultiSelectDialogField before selecting from those values ? I tried with initialValue but couldn't achieve it. Can you help me with this ?
