### ISSUE TITLE
initialValue not work in MultiSelectChipField

### ISSUE THREAD

**Issue by msaber2015** [CHB61/multi_select_flutter#11]

**Comment by John-King-456** [comment]
initialValue also not working in MultiSelectDialogField. Thanks.

**Comment by augb** [comment]
Could [this](https://github.com/CHB61/multi_select_flutter/blob/4f110b8f7fad33894b2b32a48cb1cbaeaa0a02d5/lib/dialog/multi_select_dialog_field.dart#L285) be the reason?

```
Widget _buildInheritedChipDisplay() {
  List<MultiSelectItem<V>> chipDisplayItems = [];
  chipDisplayItems = _selectedItems
      .map((e) => widget.items
          .firstWhere((element) => e == element.value, orElse: () => null))
      .toList();
  chipDisplayItems.removeWhere((element) => element == null);
```

Could it be that support for a [Comparable](https://api.flutter.dev/flutter/dart-core/Comparable-class.html) object is necessary?

**Comment by augb** [comment]
Getting back to looking at this, a simple solution that doesn't require change the library would be to override the [== operator](https://api.flutter.dev/flutter/widgets/Widget/operator_equals.html) (and, therefore, also [hashCode](https://api.flutter.dev/flutter/widgets/Widget/hashCode.html)).

(I'm new to Dart/Flutter so this was not immediately obvious to me.)

**Comment by taufan-mft** [comment]
Thanks @augb for pointing me in the right direction. For anyone that might stumbled upon this, the solution is to override the == operator and hashCode just like augb said. For example:
```dart
class Person {
  final String name;

  const Person(this.name);

  @override
  bool operator ==(Object other) =>
    identical(this, other) ||
    other is Person &&
    runtimeType == other.runtimeType &&
    name == other.name;

  @override
  int get hashCode => name.hashCode;
}
```

**Comment by altafkhan8719** [comment]
i am also facing same issue,
even after overriding == operator

**Comment by CHB61** [comment]
Hello, I'm trying to reproduce this issue. Can someone please provide a code example where this is failing?

I'm using version 3.1.6 and have tried a couple simple examples.

``` dart
// setting the entire list as initial value
MultiSelectChipField(
    items: _items,
    initialValue: _animals,
    onSaved: (val) {
        _selectedAnimals = val;
    },
)
```
``` dart
// setting a couple values from the list
MultiSelectDialogField(
    onConfirm: (val) {
        _selectedAnimals = val;
    },
    items: _items,
    initialValue: [_animals[0], _animals[2]],
),
```
``` dart
// setting the _selectedAnimals3 to desired pre-selected values list in initState - recommended
MultiSelectBottomSheetField(
    onConfirm: (values) {
        _selectedAnimals3 = values;
    },
    items: _items,
    initialValue: _selectedAnimals3,
    chipDisplay: MultiSelectChipDisplay(
        onTap: (item) {
            _selectedAnimals3.remove(item);
            return _selectedAnimals3;
        },
    ),
),
```
I've also tried running the example app with no issue.

**Comment by madhan-asmb** [comment]
> Hello, I'm trying to reproduce this issue. Can someone please provide a code example where this is failing?
> 
> I'm using version 3.1.6 and have tried a couple simple examples.
> 
> ```dart
> // setting the entire list as initial value
> MultiSelectChipField(
>     items: _items,
>     initialValue: _animals,
>     onSaved: (val) {
>         _selectedAnimals = val;
>     },
> )
> ```
> 
> ```dart
> // setting a couple values from the list
> MultiSelectDialogField(
>     onConfirm: (val) {
>         _selectedAnimals = val;
>     },
>     items: _items,
>     initialValue: [_animals[0], _animals[2]],
> ),
> ```
> 
> ```dart
> // setting the _selectedAnimals3 to desired pre-selected values list in initState - recommended
> MultiSelectBottomSheetField(
>     onConfirm: (values) {
>         _selectedAnimals3 = values;
>     },
>     items: _items,
>     initialValue: _selectedAnimals3,
>     chipDisplay: MultiSelectChipDisplay(
>         onTap: (item) {
>             _selectedAnimals3.remove(item);
>             return _selectedAnimals3;
>         },
>     ),
> ),
> ```
> 
> I've also tried running the example app with no issue.

3rd Code block cleared my issue (on tap of chipDisplay remove the taped initial value).

we need to add the return statement in the onTap function

Thanks, @CHB61

**Comment by CHB61** [comment]
@madhan-asmb Great! I hope this solutions works for everyone experiencing this problem. 

Going to drop a link to the first issue regarding this type of problem which provides more background.

[Issue #5 Initial value not working as expected](https://github.com/CHB61/multi_select_flutter/issues/5)

**Comment by ariefwijaya** [comment]
> initialValue also not working in MultiSelectDialogField. Thanks.

@CHB61 
Please open again this issue, initialValue Still not working for MultiSelectDialogField, can't be shown.

**Comment by saifonglee** [comment]
Thank @augb and @taufan-mft .
it worked for me.
