### ISSUE TITLE
Limit selection and Click outside modal problem

### ISSUE THREAD

**Issue by machadoapoena** [CHB61/multi_select_flutter#134]
Is there some way to limit selection ? And there is a problem when select itens and click on CANCEL button or outside dialog. When open the dialog again the itens is marked as checked

**Comment by chrisng98** [comment]
Below are my temporary solutions, I removed the cancel button and disabled the isDismissible option so the user can only click confirm to avoid this issue.

Go to multi_select_bottom_sheet_field.dart, add isDismissible: false in the _showBottomSheet() method. (you may customise it by passing the parameters).

Go to multi_select_bottom_sheet.dart, remove the TextButton of onCancelTap
Expanded(
                      child: TextButton(
                        onPressed: () {
                          widget.onCancelTap(context, widget.initialValue);
                          if(widget.initialValue != _selectedValues){
                            setState(() {
                              _selectedValues = widget.initialValue;
                            });
                          }
                        },
                        child: widget.cancelText ??
                            Text(
                              "CANCEL",
                              style: TextStyle(
                                color: (widget.selectedColor != null &&
                                        widget.selectedColor !=
                                            Colors.transparent)
                                    ? widget.selectedColor!.withOpacity(1)
                                    : Theme.of(context).primaryColor,
                              ),
                            ),
                      ),
                    ),
                    SizedBox(width: 10),
or you can hide it by passing parameters as well.

This should work now.
<img width="413" alt="Screenshot 2022-11-01 at 6 37 44 PM" src="https://user-images.githubusercontent.com/101167187/199215154-55d46a3c-2efd-4b99-a86a-a523782b4cd0.png">

**Comment by CHB61** [comment]
Hello,

Currently there is no way to limit selection, but I created a separate issue for that which I'll link here: [Issue #147](https://github.com/CHB61/multi_select_flutter/issues/147).

The bug about items remaining selected after cancel is fixed in version 4.1.3. I also added a `isDismissible` parameter to `MultiSelectDialogField `and `MultiSelectBottomSheetField`.
