### ISSUE TITLE
dynamically changing list of items for ( items: ) does not update UI accordingly using MultiSelectChipField<T>

### ISSUE THREAD

**Issue by AbdurrehmanSubhani** [CHB61/multi_select_flutter#136]
So what im trying to do is filter lists of topics based on the the value of a selected subject through a map:
 Map<String, List<Topic?>> subjectTopics = {
    "": [Topic(id: 1, name: "Choose a subject")],
    "Chemistry": [
      Topic(id: 1, name: "Moles"),
    ],
    "Maths": [
      Topic(id: 1, name: "Series"),
      Topic(id: 2, name: "Polynomials"),
    ]
  };

List<Topic?> topics = subjectTopics[selectedSubject];

I update the value of the selected subject through setstate and then re-assign topics with the corresponding values from the map into a list.
The widget im trying to use is MultiSelectChipField<Topic?> which upon the initialised state displays the correct values however if I update the selected subject through setState the UI does not get updated.
The exception i get is "Looking up a deactivated widget's ancestor is unsafe", I have tried adding my map to didChangeDependancy as well however it did not work.
Is there any way i can update the MultiSelectChipField UI via changing the items: ? Any help would me much appreciated.

**Comment by nerocil** [comment]
Same problem here !
Did you find solution for this?

**Comment by AbdurrehmanSubhani** [comment]
Unfortunately not as of now

> Same problem here !
> Did you find solution for this?

**Comment by CHB61** [comment]
Hello, please try again with version 4.1.3.
