### ISSUE TITLE
Hey! Please update update the package and release a new one with Flutter 3.0 Compatibility

### ISSUE THREAD

**Issue by pruthvi1698** [CHB61/multi_select_flutter#146]
: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
../…/chip_field/multi_select_chip_field.dart:273
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1

      WidgetsBinding.instance!.addPostFrameCallback((_) => _scrollToPosition());

**Comment by CHB61** [comment]
Hello, please try with version 4.1.3. Thanks

**Comment by pruthvi1698** [comment]
Thank You
