### ISSUE TITLE
Items removal upon tapping does not work.

### ISSUE THREAD

**Issue by nxr836** [CHB61/multi_select_flutter#19]
MultiSelectDialogField, some initial values are provided. In the MultiSelectChipDisplay's onTap method, the removal is wrapped with setstate (this does slow down the UI refreshment).

Upon clicking on initial items,  they are not removed, but the validator complains 'no items selected'.

But, if no initial values provided, it works perfectly.

**Comment by madhan-asmb** [comment]
`// setting the _selectedAnimals3 to desired pre-selected values list in initState - recommended
MultiSelectBottomSheetField(
    onConfirm: (values) {
        _selectedAnimals3 = values;
    },
    items: _items,
    initialValue: _selectedAnimals3,
    chipDisplay: MultiSelectChipDisplay(
        onTap: (item) {
            _selectedAnimals3.remove(item);
            return _selectedAnimals3;
        },
    ),
),`

Try this code

**Comment by nxr836** [comment]
> ```dart
> // setting the _selectedAnimals3 to desired pre-selected values list in initState - recommended
> MultiSelectBottomSheetField(
>     onConfirm: (values) {
>         _selectedAnimals3 = values;
>     },
>     items: _items,
>     initialValue: _selectedAnimals3,
>     chipDisplay: MultiSelectChipDisplay(
>         onTap: (item) {
>             _selectedAnimals3.remove(item);
>             return _selectedAnimals3;
>         },
>     ),
> ),
> ```
> 
> Try this code
> 
> add the return statement in onTap

Wow! It works, it seems the last 'return' did the job. Thanks bro! But how did you figure it out?

**Comment by madhan-asmb** [comment]
Check out this #11 issue, you will get to know how I figured out

**Comment by CHB61** [comment]
@madhan-asmb Thanks :) 

Going to drop a link to the first issue regarding this type of problem which provides more background.

Issue #5 Initial value not working as expected

**Comment by ronytesler** [comment]
Spent hours before getting here, maybe a better documentation could help.
