### ISSUE TITLE
Color per chip

### ISSUE THREAD

**Issue by fhuonder** [CHB61/multi_select_flutter#3]
Hi,

Currently it is possible to define one color for the chips.
Would be great if the color can be defined for each chip (maybe based on the value of the item. The color should apply in the `MultiSelectChipDisplay` and the select dialog.
A function could be provided that chooses the color based on the item's value. The current `chipColor` is a fallback when the function is not defined or does not return with a result.

Regards,
Florian

**Comment by CHB61** [comment]
@fhuonder Hi Florian, 

This feature is now available in version 2.1.0

The `colorator` parameter is available on all widgets.

It works just like FormField's validator, hence the name.

When using it with the MultiSelectChipDisplay, it will change the color of the chip body and text.
When using it with the Dialog or BottomSheet, it will also do that, or change the color of the checkbox if it's a LIST type.

MultiSelectChipDisplay has a textStyle param. This will take precedence for the text color over the colorator param.

![image](https://user-images.githubusercontent.com/22506965/90994824-0cb93a00-e588-11ea-9ad6-4b4d29175f9a.png)

In the example image, I have a textStyle.color of white, and a colorator that returns red for the "Frog" value.

A breakdown:

#### Priority for styling MultiSelectChipDisplay
- color of the chip body
	- colorator
	- chipColor
	- default - primaryColor
- color of the text
	- textStyle.color
	- colorator
	- chipColor
	- default - primaryColor

#### Priority for MultiSelectDialog / MultiSelectBottomSheet
- color of the chip body, chip text, checkbox
	- colorator
	- selectedColor
	- default - primaryColor

I would love to hear your feedback. You're welcome to contact me by email at ch.botha61@gmail.com.

Thanks.

Chris

**Comment by fhuonder** [comment]
Hi,

Thanks a lot. I'll look into it this week and let you know :)

Regards,
Florian

**Comment by fhuonder** [comment]
Hi,

I upgraded to version 2.1.0 and can now colorize each chip as I'd like. Works as expected.
Thanks a lot.

Regards,
Florian

**Comment by CHB61** [comment]
@fhuonder Just uploaded 2.1.1 with a small patch...

>When colorator is applied to Field or FormField, apply the same colorator to the chipDisplay if there is one. 
>
>Previously, when using a MultiSelectDialogField with a chipDisplay and you wanted the same effect both within the dialog and >on the chipDisplay, you would have to define the colorator for both widgets. This is repetitive and not ideal. Now, the >MultiSelectChipDisplay inherits the colorator from the parent field, and can still override that with the use of its own colorator.

**Comment by fhuonder** [comment]
Thanks for the update.
