### ISSUE TITLE
type 'List<Animal?>' is not a subtype of type 'List<Animal>?' of 'value'

### ISSUE THREAD

**Issue by Abhijit-Revamp** [CHB61/multi_select_flutter#34]
Here is my code

```
MultiSelectDialogField(
  listType: MultiSelectListType.LIST,
  items: _itemList
      .map((e) => MultiSelectItem(
          e, e.name ?? "--"))
      .toList(),
  title: Text("Sold Products"),
  selectedColor: Color(0xff72BF44),
  onConfirm: (e) {print(e);},
),

```

Error comes when **onConfirm** is called after confirming selection

Latest Flutter SDK
Channel master, 2.3.0-1.0.pre.149

**Comment by Abhijit-Revamp** [comment]
Found the answer. The elements needs actual class decoration in TWO places

Let's assume there is a list of options for class Animal, here is the updated code.

```
MultiSelectDialogField<Animal?>(
  listType: MultiSelectListType.LIST,
  items: _itemList
      .map((e) => MultiSelectItem<Animal?>(
          e, e.name ?? "--"))
      .toList(),
  title: Text("Sold Products"),
  selectedColor: Color(0xff72BF44),
  onConfirm: (e) {print(e);},
),

```

**Comment by aamancio** [comment]
> Found the answer. The elements needs actual class decoration in TWO places
> 
> Let's assume there is a list of options for class Product, here is the updated code.
> 
> ```
> MultiSelectDialogField< Product?>(
>   listType: MultiSelectListType.LIST,
>   items: _itemList
>       .map((e) => MultiSelectItem< Product?>(
>           e, e.name ?? "--"))
>       .toList(),
>   title: Text("Sold Products"),
>   selectedColor: Color(0xff72BF44),
>   onConfirm: (e) {print(e);},
> ),
> ```

That works thanks.
