### ISSUE TITLE
dialog height too big

### ISSUE THREAD

**Issue by Hosam11** [CHB61/multi_select_flutter#35]
how to remove this empty area from dialog ?

![multiseclect dropdown](https://user-images.githubusercontent.com/18370055/117171557-430fb000-adcb-11eb-83a1-31ce89c7b805.PNG)

**Comment by vcestra** [comment]
I have the same problem. How do you fix @Hosam11 ? Thanks

**Comment by Hosam11** [comment]
@vcestra  there is an height attribute you can give it double value

**Comment by vcestra** [comment]
Ok @Hosam11 . So you fix the height. Thanks

**Comment by Hosam11** [comment]
in version 3.1.7 the dialog height  is fit to  content of element  inside the dropdown dialog and the below code work fine
**MultiSelectDialog.dart** in build method inside alert dialog the content
```
  content: Container(
        height: widget.height,
        child: SingleChildScrollView(
          child: widget.listType == null ||
                  widget.listType == MultiSelectListType.LIST
              ? ListTileTheme(
                  contentPadding: EdgeInsets.fromLTRB(14.0, 0.0, 24.0, 0.0),
                  child: ListBody(
                    children: _items.map(_buildListItem).toList(),
                  ),
                )
              : Wrap(
                  children: _items.map(_buildChipItem).toList(),
                ),
        ),
      ),
```
so please replace the new version of code with the old version inside that class

**Comment by NRMrYang** [comment]
@Hosam11 Hi, I use 4.1.2 ,and find `content` still uses  `Container` instead of `Column` , should i alert source code?

**Comment by NRMrYang** [comment]
I have tried `wrap the Container with Column then give it MainAxisSize.min, then make ListView shrinkWrap: true`. If height is null, there is errors.I believe following steps will helps.
1. wrap the Container with ConstrainedBox
2. set minHeight: 0
3. make ListView shrinkWrap: true
```dart
      content: ConstrainedBox(
        constraints: BoxConstraints(
          minHeight: 0,
        ),
        child: Container(
          height: widget.height,
          width: widget.width ?? MediaQuery.of(context).size.width * 0.73,
          child: widget.listType == null ||
              widget.listType == MultiSelectListType.LIST
              ? ListView.builder(
            itemCount: _items.length,
            shrinkWrap: true,
            itemBuilder: (context, index) {
              return _buildListItem(_items[index]);
            },
          )
              : SingleChildScrollView(
            child: Wrap(
              children: _items.map(_buildChipItem).toList(),
            ),
          ),
        ),
      ),
```
