### ISSUE TITLE
specifying icon parameter in MultiSelectChipDisplay() throws error

### ISSUE THREAD

**Issue by vaibhav891** [CHB61/multi_select_flutter#4]
When trying to pass newly added icon parameter in MultiSelectChipDisplay() class throws an error like below -
`The method 'call' was called on null.
Receiver: null
Tried calling: call(Instance of 'Animal')
The relevant error-causing widget was
    MultiSelectChipDisplay<dynamic> 
`
I have used the example code as it is and just added icon parameter as below.
`chipDisplay: MultiSelectChipDisplay(
                        icon: Icon(Icons.access_alarm),
                        items: _selectedAnimals2
                            .map((e) => MultiSelectItem<Animal>(e, e.name))
                            .toList(),
                        onTap: (value) {
                          setState(() {
                            _selectedAnimals2.remove(value);
                          });
                        },
                      ),`

Flutter doctor -v output
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G2021, locale en-IN)
    • Flutter version 1.20.3 at /Users/vaibhav/Documents/flutter
    • Framework revision 216dee60c0 (12 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/vaibhav/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/vaibhav/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554                        • android-x86 • Android 7.1.1 (API 25) (emulator)
    • iPhone 11 (mobile)                 • 8F609EB6-6129-4CF3-82AD-6381BAF858D4 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-6
      (simulator)

• No issues found!

**Comment by CHB61** [comment]
Hi @vaibhav891,

Thanks for pointing this out! I was able to recreate the issue and released a fix for it in version 2.3.0.
Please review the change here - [Changelog](https://pub.dev/packages/multi_select_flutter/changelog)

- Chris
