### ISSUE TITLE
Example doesn't work:  Expected a value of type 'List<Animal>?', but got one of type 'List<Animal?>'

### ISSUE THREAD

**Issue by mrgithub** [CHB61/multi_select_flutter#46]
Get this error when trying to run the example

======== Exception caught by gesture ===============================================================
The following TypeErrorImpl was thrown while handling a gesture:
Expected a value of type 'List<Animal>?', but got one of type 'List<Animal?>'

What's going wrong?

 MultiSelectDialogField(
            items: _items,
            title: Text("Main Categories"),
            selectedColor: Colors.pink,
            decoration: BoxDecoration(
              color: Colors.pink.withOpacity(0.1),
              borderRadius: BorderRadius.all(Radius.circular(40)),
              border: Border.all(
                color: Colors.pink,
                width: 2,
              ),
            ),
            buttonIcon: Icon(
              Icons.category,
              color: Colors.pink,
            ),
            buttonText: Text(
              "Main Categories - high level categories to list the card in",
              style: TextStyle(
                  //color: Colors.blue[800],
                  //fontSize: 16,
                  ),
            ),
            onConfirm: (results) {
             var selected = results.cast();
            }),

**Comment by salamaabid** [comment]
Could you please try with 

 final _items = _animals
      .map((animal) => MultiSelectItem<Animal?>(animal, animal.name))
      .toList();

**Comment by mrgithub** [comment]
That worked!

**Comment by mrgithub** [comment]
That worked!!
