### ISSUE TITLE
module error.

### ISSUE THREAD

**Issue by johnfriend** [CHB61/multi_select_flutter#6]
When I install and run this module, I am getting the following error.

../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/multi_select_flutter-3.1.3/lib/dialog/multi_select_dialog_field.dart:92:9: Error: Type 'AutovalidateMode' not found.
  final AutovalidateMode autovalidateMode;
        ^^^^^^^^^^^^^^^^
../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/multi_select_flutter-3.1.3/lib/bottom_sheet/multi_select_bottom_sheet_field.dart:101:9: Error: Type 'AutovalidateMode' not found.
  final AutovalidateMode autovalidateMode;
        ^^^^^^^^^^^^^^^^
../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/multi_select_flutter-3.1.3/lib/chip_field/multi_select_chip_field.dart:83:9: Error: Type 'AutovalidateMode' not found.
  final AutovalidateMode autovalidateMode;
        ^^^^^^^^^^^^^^^^
../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/multi_select_flutter-3.1.3/lib/dialog/multi_select_dialog_field.dart:92:9: Error: 'AutovalidateMode' isn't a type.
  final AutovalidateMode autovalidateMode;
        ^^^^^^^^^^^^^^^^
../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/multi_select_flutter-3.1.3/lib/dialog/multi_select_dialog_field.dart:128:29: Error: Getter not found: 'AutovalidateMode'.
    this.autovalidateMode = AutovalidateMode.disabled,
                            ^^^^^^^^^^^^^^^^
../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/multi_select_flutter-3.1.3/lib/dialog/multi_select_dialog_field.dart:134:13: Error: No named parameter with the name 'autovalidateMode'.
            autovalidateMode: autovalidateMode,
            ^^^^^^^^^^^^^^^^
../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/multi_select_flutter-3.1.3/lib/bottom_sheet/multi_select_bottom_sheet_field.dart:101:9: Error: 'AutovalidateMode' isn't a type.
  final AutovalidateMode autovalidateMode;
        ^^^^^^^^^^^^^^^^
../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/multi_select_flutter-3.1.3/lib/bottom_sheet/multi_select_bottom_sheet_field.dart:141:29: Error: Getter not found: 'AutovalidateMode'.
    this.autovalidateMode = AutovalidateMode.disabled,
                            ^^^^^^^^^^^^^^^^
../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/multi_select_flutter-3.1.3/lib/bottom_sheet/multi_select_bottom_sheet_field.dart:146:13: Error: No named parameter with the name 'autovalidateMode'.
            autovalidateMode: autovalidateMode,
            ^^^^^^^^^^^^^^^^
../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/multi_select_flutter-3.1.3/lib/chip_field/multi_select_chip_field.dart:83:9: Error: 'AutovalidateMode' isn't a type.
  final AutovalidateMode autovalidateMode;
        ^^^^^^^^^^^^^^^^
../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/multi_select_flutter-3.1.3/lib/chip_field/multi_select_chip_field.dart:111:29: Error: Getter not found: 'AutovalidateMode'.
    this.autovalidateMode = AutovalidateMode.disabled,
                            ^^^^^^^^^^^^^^^^
../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/multi_select_flutter-3.1.3/lib/chip_field/multi_select_chip_field.dart:123:13: Error: No named parameter with the name 'autovalidateMode'.
            autovalidateMode: autovalidateMode,

**Comment by fabton1963** [comment]
I get the same error too.

**Comment by fabton1963** [comment]
I solved with flutter upgrade.

**Comment by srijanlama** [comment]
i m facing similar issue ``` /C:/flutter/.pub-cache/hosted/pub.dartlang.org/multi_select_flutter-3.1.8/lib/dialog/multi_select_dialog_field.dart:93:9: Error: Type 'AutovalidateMode' not found.``` 
my flutter doctor config
```
Flutter 1.20.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 840c9205b3 (1 year, 10 months ago) • 2020-08-04 20:55:12 -0700
Engine • revision c8e3b94853
Tools • Dart 2.9.0
```

any help appeciated thanks
