### ISSUE TITLE
Example using initialValue in MultiSelectDialogField

### ISSUE THREAD

**Issue by Aynn** [CHB61/multi_select_flutter#7]
I have been struggling a bit getting initial value to work, could someone provide an example?

I don't see it being used in any of the examples in the repository.

**Comment by CHB61** [comment]
Hi @Aynn,

I'm sorry to respond so late.

I have updated the example project to include a MultiSelectDialogField that has initial values set.

Here is an example:

```
MultiSelectBottomSheetField(
  items: _animalItems,
  initialValue: _selectedAnimals // set this in initState for pre-selected values,
  onConfirm: (values) {
    _selectedAnimals = values;
  },
  chipDisplay: MultiSelectChipDisplay(
    onTap: (item) {
      _selectedAnimals.remove(item);
      return _selectedAnimals;
    },
  ),
),
```

Hope this helps :)

**Comment by ariefwijaya** [comment]
@CHB61  The issue is still exist for me, initialValue can't be shown
