### ISSUE TITLE
Help Convert List<dynamic> to List<MultiSelectItem<dynamic>>

### ISSUE THREAD

**Issue by johnfriend88** [CHB61/multi_select_flutter#9]
Hi 
I have Json data of list. I want to convert into List<MultiSelectItem<dynamic>> so that items will accept. 

can you help me on this.

Please find below Json output

[{id: 1, name: apple}, {id: 2, name: orange}, {id: 3, name: Mango}, {id: 4, name: Papaya}, {id: 5, name: carrot}]

**Comment by CHB61** [comment]
Hey @johnfriend88,

```
    List fruitList = [
      {"id": 1, "name": "Apple"},
      {"id": 2, "name": "Orange"},
      {"id": 3, "name": "Mango"},
      {"id": 4, "name": "Papaya"},
      {"id": 5, "name": "Carrot"},
    ];

    List<MultiSelectItem> _items = fruitList.map((e) => MultiSelectItem(e['id'], e['name'])).toList();

    MultiSelectDialogField(
        items: _items,
    ),
```
This code is working for me but I would recommend creating a model class that has methods for `toJson()` and `fromJson()`.

Hope this helps!
