### ISSUE TITLE
Set when loading checked option

### ISSUE THREAD

**Issue by jcardonne** [CHB61/multi_select_flutter#95]
I'm using a MultiSelectDialogField and I would like to set the options which are already checked or not. But I don't think anything was designed for it. Is it possible ?

**Comment by skillitzimberg** [comment]
@jcardonne, [I posted on SO](https://stackoverflow.com/questions/71712628/how-to-persist-and-display-selected-items-in-multi-select-flutter-widget) for something that might be similar. Are you having this, or similar, issue when pulling from a data source?

**Comment by jcardonne** [comment]
> @jcardonne, [I posted on SO](https://stackoverflow.com/questions/71712628/how-to-persist-and-display-selected-items-in-multi-select-flutter-widget) for something that might be similar. Are you having this, or similar, issue when pulling from a data source?

I looked at your thread and saw that I forgot to add the **initialValue** parameter, that's why. Now it's work for me
